/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SiteCurrency } from "./SiteCurrency";
import { SiteCurrencyCountArgs } from "./SiteCurrencyCountArgs";
import { SiteCurrencyFindManyArgs } from "./SiteCurrencyFindManyArgs";
import { SiteCurrencyFindUniqueArgs } from "./SiteCurrencyFindUniqueArgs";
import { DeleteSiteCurrencyArgs } from "./DeleteSiteCurrencyArgs";
import { SiteCurrencyService } from "../siteCurrency.service";
@graphql.Resolver(() => SiteCurrency)
export class SiteCurrencyResolverBase {
  constructor(protected readonly service: SiteCurrencyService) {}

  async _siteCurrenciesMeta(
    @graphql.Args() args: SiteCurrencyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SiteCurrency])
  async siteCurrencies(
    @graphql.Args() args: SiteCurrencyFindManyArgs
  ): Promise<SiteCurrency[]> {
    return this.service.siteCurrencies(args);
  }

  @graphql.Query(() => SiteCurrency, { nullable: true })
  async siteCurrency(
    @graphql.Args() args: SiteCurrencyFindUniqueArgs
  ): Promise<SiteCurrency | null> {
    const result = await this.service.siteCurrency(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SiteCurrency)
  async deleteSiteCurrency(
    @graphql.Args() args: DeleteSiteCurrencyArgs
  ): Promise<SiteCurrency | null> {
    try {
      return await this.service.deleteSiteCurrency(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
